[package]
name = "voting-dapp"
version = "1.0.0"
authors = []

[addresses]
NFTMarket = "0xe9c0c69b92cd4937ee32cefb571cb7ad10d155edfbabdfe0d65bef7771a9d1d6"
my_addrx = "0xe9c0c69b92cd4937ee32cefb571cb7ad10d155edfbabdfe0d65bef7771a9d1d6"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
